# Generated by Django 6.0.3 on 2026-04-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выходного')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
