# Generated by Django 6.0.3 on 2026-03-24 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performedprocedure',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выполнения'),
        ),
    ]
